### ISSUE TITLE
No output file will be generated at all

### ISSUE THREAD

**Issue by oqq** [prooph/message-flow-analyzer#3]
If I run
```bash
$ vendor/bin/prooph-analyzer project:analyze src -vvv
```
OR
```bash
$ vendor/bin/prooph-analyzer project:analyze src -vvv -o test.json
```

I got the following output:
```
Analyzing project dir /Users/***/Projects/***/src
Using config ./prooph_analyzer.json
```

But then nothing happened. 
There is neither a test.json nor a prooph_message_flow.json created.

Also there is no error in output.

**Comment by codeliner** [comment]
The command does not reach this line: https://github.com/prooph/message-flow-analyzer/blob/master/src/Cli/AnalyzeProjectCommand.php#L90

So I guess there occurs an error during execution. If you cannot see anything maybe your PHP settings hide errors (display_errors = 0)?

**Comment by codeliner** [comment]
Or does the process never stop?

**Comment by oqq** [comment]
Not error reporting was an issue, but memory limit.
After increasing the default value (much), an output file was generated.

Not really a bug, but also important in a later improvement step.
Closed for now, since issue description is invalid.
